/**
 * Diccionario de palabras comunes que necesitan tilde en español
 * Mapea la forma sin tilde → forma con tilde correcta
 */
const ACCENT_MAP: Record<string, string> = {
  // Palabras básicas
  'parana': 'Paraná',
  'municipalidad': 'Municipalidad',
  'municipio': 'Municipio',
  'nacion': 'Nación',
  'provincia': 'Provincia',
  'provincias': 'Provincias',
  'region': 'Región',
  'regiones': 'Regiones',
  'capital': 'Capital',
  'administracion': 'Administración',
  'administraciones': 'Administraciones',
  'educacion': 'Educación',
  'salud': 'Salud',
  'seguridad': 'Seguridad',
  'justicia': 'Justicia',
  'policia': 'Policía',
  'hospital': 'Hospital',
  'escuela': 'Escuela',
  'universidad': 'Universidad',
  'ministerio': 'Ministerio',
  'gobierno': 'Gobierno',
  'estado': 'Estado',
  'estados': 'Estados',
  'federacion': 'Federación',
  'sindicato': 'Sindicato',
  'union': 'Unión',
  'asociacion': 'Asociación',
  'cooperativa': 'Cooperativa',
  'empresa': 'Empresa',
  'empresas': 'Empresas',
  'fundacion': 'Fundación',
  'organizacion': 'Organización',
  'institucion': 'Institución',
  'instituto': 'Instituto',
  'centro': 'Centro',
  'centros': 'Centros',
  'agencia': 'Agencia',
  'direccion': 'Dirección',
  'gerencia': 'Gerencia',
  'jefatura': 'Jefatura',
  'secretaria': 'Secretaría',
  'subsecretaria': 'Subsecretaría',
  'subdireccion': 'Subdirección',
  'coordinacion': 'Coordinación',
  'departamento': 'Departamento',
  'division': 'División',
  'seccion': 'Sección',
  'area': 'Área',
  'comision': 'Comisión',
  'comite': 'Comité',
  'consejo': 'Consejo',
  'juzgado': 'Juzgado',
  'judicial': 'Judicial',
  'tribunal': 'Tribunal',
  'corte': 'Corte',
  'fiscalia': 'Fiscalía',
  'defensoria': 'Defensoría',
  'procuraduria': 'Procuraduría',
  'tesoreria': 'Tesorería',
  'contaduria': 'Contaduría',
  'auditoria': 'Auditoría',
  'contraloria': 'Contraloría',
  'intendencia': 'Intendencia',
  'municipal': 'Municipal',
  'provincial': 'Provincial',
  'nacional': 'Nacional',
  'regional': 'Regional',
  'local': 'Local',
  'general': 'General',
  'especial': 'Especial',
  'particular': 'Particular',
  'publico': 'Público',
  'publica': 'Pública',
  'publicos': 'Públicos',
  'publicas': 'Públicas',
  'privado': 'Privado',
  'privada': 'Privada',
  'privados': 'Privados',
  'privadas': 'Privadas',

  // Nombres comunes argentinos
  'ramirez': 'Ramírez',
  'gomez': 'Gómez',
  'rodriguez': 'Rodríguez',
  'martinez': 'Martínez',
  'lopez': 'López',
  'gonzalez': 'González',
  'garcia': 'García',
  'fernandez': 'Fernández',
  'diaz': 'Díaz',
  'alvarez': 'Álvarez',
  'perez': 'Pérez',
  'sanchez': 'Sánchez',
  'romero': 'Romero',
  'ruiz': 'Ruiz',
  'torres': 'Torres',
  'benitez': 'Benítez',
  'acosta': 'Acosta',
  'arias': 'Arias',
  'medina': 'Medina',
  'heredia': 'Heredia',
  'cardozo': 'Cardozo',
  'vazquez': 'Vázquez',
  'rojas': 'Rojas',
  'suarez': 'Suárez',
  'reyes': 'Reyes',
  'chavez': 'Chávez',
  'paz': 'Paz',
  'flores': 'Flores',
  'espindola': 'Espíndola',
  'espinoza': 'Espinoza',
  'cordova': 'Córdoba',
  'figueroa': 'Figueroa',
  'guzman': 'Guzmán',
  'navarro': 'Navarro',
  'castro': 'Castro',
  'ortiz': 'Ortiz',
  'rios': 'Ríos',
  'silva': 'Silva',
  'vargas': 'Vargas',
  'molina': 'Molina',
  'vega': 'Vega',
  'cabrera': 'Cabrera',
  'herrera': 'Herrera',
  'aguilar': 'Aguilar',
  'sosa': 'Sosa',
  'blas': 'Blas',
  'pereyra': 'Pereyra',
  'bravo': 'Bravo',
  'carrizo': 'Carrizo',
  'juarez': 'Juárez',
  'ibarra': 'Ibarra',
  'montes': 'Montes',
  'nieves': 'Nieves',
  'olivera': 'Olivera',
  'quinteros': 'Quinteros',
  'robles': 'Robles',
  'zalazar': 'Zalazar',

  // Palabras con tilde diacrítica
  // NOTA: palabras monosílabas como el/él, mi/mí, de/dé, se/sé, tu/tú, te/té, si/sí
  // se omiten porque la tilde es contextual y la corrección automática
  // genera más errores de los que resuelve.
  'mas': 'más',
  'aun': 'aún',
  'tambien': 'también',
  'despues': 'después',
  'manana': 'mañana',
  'dia': 'día',
  'dias': 'días',
  'anio': 'año',
  'anios': 'años',

  // Verbos comunes
  'tiene': 'tiene',
  'fue': 'fue',
  'es': 'es',
  'son': 'son',
  'esta': 'está',
  'estas': 'estás',
  'estamos': 'estamos',
  'estan': 'están',
  'estoy': 'estoy',
  'sera': 'será',
  'seran': 'serán',
  'estara': 'estará',
  'estaran': 'estarán',
  'tuvo': 'tuvo',
  'hicimos': 'hicimos',
  'hizo': 'hizo',
  'dijo': 'dijo',
  'vino': 'vino',
  'salio': 'salió',
  'llego': 'llegó',
  'pudo': 'pudo',
  'quiso': 'quiso',

  // Otras palabras frecuentes
  'numero': 'número',
  'telefono': 'teléfono',
  'electronico': 'electrónico',
  'electronica': 'electrónica',
  'automatico': 'automático',
  'automatica': 'automática',
  'practico': 'práctico',
  'practica': 'práctica',
  'tecnico': 'técnico',
  'tecnica': 'técnica',
  'analisis': 'análisis',
  'crisis': 'crisis',
  'tesis': 'tesis',
  'metodo': 'método',
  'metodos': 'métodos',
  'sistema': 'sistema',
  'sistemas': 'sistemas',
  'problema': 'problema',
  'problemas': 'problemas',
  'programa': 'programa',
  'programas': 'programas',
  'diagnostico': 'diagnóstico',
  'diagnosticos': 'diagnósticos',
  'pronostico': 'pronóstico',
  'pronosticos': 'pronósticos',
  'deposito': 'depósito',
  'depositos': 'depósitos',
  'credito': 'crédito',
  'creditos': 'créditos',
  'debito': 'débito',
  'debitos': 'débitos',
  'interes': 'interés',
  'intereses': 'intereses',
  'monto': 'Monto',
  'total': 'Total',
  'parcial': 'Parcial',
  'proyeccion': 'Proyección',
  'proyecciones': 'Proyecciones',
  'venta': 'Venta',
  'ventas': 'Ventas',
  'compra': 'Compra',
  'compras': 'Compras',
  'pago': 'pago',
  'pagos': 'Pagos',
  'cobro': 'cobro',
  'cobros': 'Cobros',
  'cuota': 'Cuota',
  'cuotas': 'Cuotas',
  'plan': 'Plan',
  'planes': 'Planes',
  'gestion': 'gestión',
  'gestiones': 'gestiones',
  'conversion': 'conversión',
  'conversiones': 'conversiones',
  'atencion': 'atención',
  'evaluacion': 'evaluación',
  'revision': 'revisión',
  'aprobacion': 'aprobación',
  'autorizacion': 'autorización',
  'cancelacion': 'cancelación',
  'confirmacion': 'confirmación',
  'notificacion': 'notificación',
  'observacion': 'observación',
  'observaciones': 'observaciones',
  'comentario': 'Comentario',
  'comentarios': 'Comentarios',
  'nota': 'Nota',
  'notas': 'Notas',
  'informe': 'Informe',
  'informes': 'Informes',
  'reporte': 'Reporte',
  'reportes': 'Reportes',
  'resumen': 'Resumen',
  'resumenes': 'Resúmenes',
  'detalle': 'Detalle',
  'detalles': 'Detalles',
  'descripcion': 'Descripción',
  'descripciones': 'Descripciones',
  'relacion': 'Relación',
  'relaciones': 'Relaciones',
  'ubicacion': 'Ubicación',
  'ubicaciones': 'Ubicaciones',
  'posicion': 'Posición',
  'posiciones': 'Posiciones',
  'situacion': 'Situación',
  'situaciones': 'Situaciones',
  'condicion': 'Condición',
  'condiciones': 'Condiciones',
  'decision': 'Decisión',
  'decisiones': 'Decisiones',
  'accion': 'Acción',
  'acciones': 'Acciones',
  'reclamo': 'Reclamo',
  'reclamos': 'Reclamos',
  'satisfaccion': 'satisfacción',
  'desempeno': 'desempeño',
  'desvios': 'desvíos',
  'desvio': 'desvío',
  'logros': 'Logros',
  'logro': 'Logro',
  'periodo': 'período',
  'periodos': 'períodos',
  'trimestre': 'Trimestre',
  'semestre': 'Semestre',
  'trimestral': 'Trimestral',
  'semestral': 'Semestral',
  'anual': 'Anual',
  'mensual': 'Mensual',
  'semanal': 'Semanal',
  'diario': 'Diario',
  'diaria': 'Diaria',
};

/**
 * Corrige automáticamente las tildes en un texto
 * Busca palabras en el diccionario y las reemplaza por su forma correcta
 */
export function corregirTildes(texto: string): string {
  if (!texto) return texto;

  let resultado = texto;

  // Recorrer el diccionario y reemplazar coincidencias
  for (const [sinTilde, conTilde] of Object.entries(ACCENT_MAP)) {
    // Crear regex que busca la palabra completa (case insensitive)
    const regex = new RegExp(`\\b${sinTilde}\\b`, 'gi');
    resultado = resultado.replace(regex, (match) => {
      // Mantener el case original
      if (match === match.toUpperCase()) {
        return conTilde.toUpperCase();
      }
      if (match[0] === match[0].toUpperCase()) {
        return conTilde.charAt(0).toUpperCase() + conTilde.slice(1);
      }
      return conTilde.toLowerCase();
    });
  }

  return resultado;
}

/**
 * Corrige tildes en tiempo real mientras el usuario escribe
 * Se aplica después de escribir la palabra completa (detecta espacios, punto, etc.)
 */
export function corregirTildesEnTiempoReal(texto: string): string {
  if (!texto) return texto;

  // Dividir por palabras y corregir cada una
  return texto.split(/(\s+|[.,;:!?()])/).map(parte => {
    if (/^\s+$/.test(parte) || /^[.,;:!?()]+$/.test(parte)) {
      return parte;
    }
    return corregirTildes(parte);
  }).join('');
}
